apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
  namespace: flask-app
spec:
  type: LoadBalancer
  selector:
    app: flask-app
  ports:
    - name: portfolio-port
      protocol: TCP
      port: 80
      targetPort: 5000
    - name: webapp-port
      protocol: TCP
      port: 443
      targetPort: 3000
